version: "3.1"

services:
  todo_api_php_service:
    container_name: todo_api_php_container
    build:
      context: .
    image: todo_api_php_image
    # Overrides the user used to run the container process. 
    # Default is that set by image (i.e. Dockerfile USER), if not set, root
    user: user
    restart: always
    ports: 
      - 8080:80
    volumes: 
      - ./src:/var/www/todo
    healthcheck:
      test: "${DOCKER_HEALTHCHECK:-curl --fail http://localhost:80 || exit 1}"
      interval: "60s"
      timeout: "15s"
      start_period: "0s"
      retries: 3
    depends_on:
      - todo_api_mariadb_service

  todo_api_mariadb_service:
    container_name: todo_api_mariadb_container
    image: mariadb
    restart: always
    ports: 
      - 3306:3306
    volumes: 
      - ./db:/var/lib/mysql:rw
    environment:
      - MYSQL_DATABASE=todo
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=dev
      - MYSQL_RANDOM_ROOT_PASSWORD=yes