version: "3.1"

services:
  todo-api-php:
    container_name: todo-api-php
    build: .
    restart: always
    ports: 
      - 8080:80
    volumes: 
      - ./src:/var/www/todo
    healthcheck:
      test: "${DOCKER_HEALTHCHECK:-curl --fail http://localhost:80 || exit 1}"
      interval: "60s"
      timeout: "15s"
      start_period: "0s"
      retries: 3
    depends_on:
      - todo-api-mariadb

  todo-api-mariadb:
    container_name: todo-api-mariadb
    image: mariadb
    restart: always
    ports: 
      - 3306:3306
    volumes: 
      - ./db:/var/lib/mysql:rw
    environment:
      - MYSQL_DATABASE=todo
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=dev
      - MYSQL_RANDOM_ROOT_PASSWORD=yes